LeiLaoExpress.UI.MVC/Controllers/OpportunityController.cs
using LeiLaoExpress.Domain.Contract.Services;
using LeiLaoExpress.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using LeiLaoExpress.Infra.Data;
using LeiLaoExpress.Domain.Enum;

namespace LeiLaoExpress.UI.MVC.Controllers
{
    [Authorize]
    public class OpportunityController : AnexoBaseController
    {
        private readonly IOportunidadeService _service;
        private readonly ICargaService _serviceCarga;
        private readonly ILanceService _serviceLance;
        private readonly IFeedbackService _serviceFeedback;

        public OpportunityController(IOportunidadeService service, ICargaService serviceCarga, ILanceService serviceLance,
            IFeedbackService serviceFeedback)
        {
            _service = service;
            _serviceCarga = serviceCarga;
            _serviceLance = serviceLance;
            _serviceFeedback = serviceFeedback;
        }

        // GET: Opportunity
        public async Task<ActionResult> Index()
        {
            var lista = await _service.GetAllAsync();

            ViewBag.IsFornecedor = TipoUsuarioLogado == TypeOfUser.Fornecedor;


            return View(lista);
        }

        public async Task<ActionResult> MinhasOportunidades()
        {
            var lista = await _service.GetAllAsync(x => x.User.Id == IdUsuarioLogado);

            return View("Lista", lista);
        }

        public ActionResult Create()
        {
            ViewBag.CargaId = new SelectList(_serviceCarga.GetAll(x => x.UserId == IdUsuarioLogado), "Id", "Nome");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Oportunidade model, int? CargaId)
        {
            if (!CargaId.HasValue)
                ModelState.AddModelError("CargaId", "Escolha uma carga.");

            if (!ModelState.IsValid)
            {
                ViewBag.CargaId = new SelectList(_serviceCarga.GetAll(x => x.UserId == IdUsuarioLogado), "Id", "Nome", CargaId);

                return View(model);
            }

            model.UserId = IdUsuarioLogado;

            var carga = _serviceCarga.GetById(CargaId.Value);

            carga.Oportunidades.Add(model);

            _serviceCarga.Update(carga);

            return RedirectToAction("MinhasOportunidades");
        }

        public async Task<ActionResult> Edit(int Id)
        {
            var model = await _service.GetByIdAsync(Id);

            ViewBag.CargaId = new SelectList(_serviceCarga.GetAll(x => x.UserId == IdUsuarioLogado), "Id", "Nome", model.Cargas.FirstOrDefault().Id);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Oportunidade model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _service.UpdateAsync(model);

            return RedirectToAction("MinhasOportunidades");
        }

        public async Task<ActionResult> Details(int Id)
        {
            var model = await _service.GetByIdAsync(Id);
            return View(model);
        }

        public ActionResult Delete(int Id)
        {
            _service.Remove(Id);

            return RedirectToAction("MinhasOportunidades");
        }

        public ActionResult DetalharOportunidade(int Id)
        {
            var model = _service.GetById(Id);

            ViewBag.IsFornecedor = TipoUsuarioLogado == TypeOfUser.Fornecedor;
            
            if (model.DataColeta.AddDays(3).Date < DateTime.Now.Date)
            {
                if (!model.Lances.Any(x => x.Escolhida))
                {
                    Lance lance = model.Lances.OrderBy(x => x.Valor).ThenByDescending(x => x.DataColeta).ThenByDescending(x => x.DataEntrega).FirstOrDefault();

                    if (lance != null)
                    {
                        lance.Escolhida = true;

                        _service.Update(model);
                    }
                }

            }

            ViewBag.Encerrada = model.Lances.Any(x => x.Escolhida);
            ViewBag.AtivarFeedback = !_serviceFeedback.GetAll(x => x.Oportunidade.Id == model.Id).Any();
            return View(model);
        }

        public ActionResult SelecionarServico(int id)
        {
            var lance = _serviceLance.GetById(id);

            if (lance == null)
                return HttpNotFound();

            var lanceEscolhido = _serviceLance.GetAll(x => x.Escolhida && x.Oportunidade.Id == lance.Oportunidade.Id).FirstOrDefault();


            if (lanceEscolhido != null)
            {

                lanceEscolhido.Escolhida = false;

                _serviceLance.Update(lanceEscolhido);
            }
            lance.Escolhida = true;

            _serviceLance.Update(lance);

            return RedirectToAction("DetalharOportunidade", new { id = lance.Oportunidade.Id });
        }

    }
}

LeiLaoExpress.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Text.NameSystem</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/appDialog")
    <link href='http://fonts.googleapis.com/css?family=Montserrat|Raleway:400,200,300,500,600,700,800,900,100' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Iceland' rel='stylesheet' type='text/css'>
</head>
<body>
    <div id="main-modal"></div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               @* @Html.ActionLink(Text.NameSystem, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <div class="head-logo">
                    <h1><a href="@Url.Action("Index", "Home", new { area = "" })">Leilão <span class="texto-branco">Express</span></a></h1>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Partial("_Menu")
                </ul>
                @*<ul class="nav navbar-nav navbar-right">*@
                    @Html.Partial("_LoginPartial")
                @*</ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - @Text.NameSystem</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/main")
    @RenderSection("scripts", required: false)
</body>
</html>

LeiLaoExpress.UI.MVC/Views/Shared/_Menu.cshtml
@using Microsoft.AspNet.Identity
@using System.Security.Claims
@{
    var identity = (ClaimsIdentity)User.Identity;

    var TypeOfUser = identity.Claims.FirstOrDefault(c => c.Type == "TypeOfUser");
}
@if (TypeOfUser != null && TypeOfUser.Value == LeiLaoExpress.Domain.Enum.TypeOfUser.Fornecedor.ToString())
{
    <li>@Html.ActionLink(Inputs.Opportunity, "Index", "Opportunity")</li>
}
else
{
    
}