LeiLaoExpress.UI.MVC/Controllers/LanceController.cs
using LeiLaoExpress.Domain.Contract.Services;
using LeiLaoExpress.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace LeiLaoExpress.UI.MVC.Controllers
{
	public class LanceController : BaseController
	{
		private readonly ILanceService _service;
		private readonly IMeioTransporteService _serviceMeioTransporte;

		public LanceController(ILanceService service, IMeioTransporteService serviceMeioTransporte)
		{
			_service = service;
			_serviceMeioTransporte = serviceMeioTransporte;
		}

		// GET: Lance
		public async Task<ActionResult> Index()
		{
			var lista = await _service.GetAllAsync(x => x.Fornecedor.UserId == IdUsuarioLogado);

			return View(lista);
		}

		public ActionResult Create(int idOportunidade)
		{
			ViewBag.idOportunidade = idOportunidade;

			ViewBag.MeioTransporteId = new SelectList(_serviceMeioTransporte.GetAll(), "Id", "Nome");

			return View();
		}

		[HttpPost]
		public ActionResult Create(Lance model)
		{
			if (!ModelState.IsValid)
			{
				ViewBag.idOportunidade = model.OportunidadeId;

				ViewBag.MeioTransporteId = new SelectList(_serviceMeioTransporte.GetAll(), "Id", "Nome", model.MeioTransporteId);

				return View(model);
			}

			model.FornecedorId = IdUsuarioLogado;

			_service.Create(model);

			return RedirectToAction("Index", "Opportunity");
		}

		public ActionResult Edit(int Id)
		{
			var model = _service.GetById(Id);

			ViewBag.idOportunidade = model.Oportunidade.Id;

			ViewBag.MeioTransporteId = new SelectList(_serviceMeioTransporte.GetAll(), "Id", "Nome", model.MeioTransporte.Id);

			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(Lance model)
		{
			if (!ModelState.IsValid)
			{
				ViewBag.idOportunidade = model.OportunidadeId;

				ViewBag.MeioTransporteId = new SelectList(_serviceMeioTransporte.GetAll(), "Id", "Nome", model.MeioTransporteId);

				return View(model);
			}

			model.FornecedorId = IdUsuarioLogado;

			_service.Update(model);

			return RedirectToAction("Index");
		}

		public ActionResult Delete(int Id)
		{
			_service.Remove(Id);

			return RedirectToAction("Index");
		}

		public PartialViewResult LanceModal(int OportunidadeId)
		{
			ViewBag.OportunidadeId = OportunidadeId;

			ViewBag.MeioTransporteId = new SelectList(_serviceMeioTransporte.GetAll(), "Id", "Nome");

			return PartialView();
		}

		[HttpPost]
		public ActionResult LanceModal(Lance model)
		{
			if (!ModelState.IsValid)
			{
				ViewBag.OportunidadeId = model.OportunidadeId;

				ViewBag.MeioTransporteId = new SelectList(_serviceMeioTransporte.GetAll(), "Id", "Nome");

				return PartialView(model);
			}

			model.FornecedorId = IdUsuarioLogado;

			_service.Create(model);

			return RedirectToAction("DetalharOportunidade", "Opportunity", new { Id = model.OportunidadeId });
		}
	}
}

LeiLaoExpress.UI.MVC/Controllers/OpportunityController.cs
using LeiLaoExpress.Domain.Contract.Services;
using LeiLaoExpress.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using LeiLaoExpress.Infra.Data;
using LeiLaoExpress.Domain.Enum;

namespace LeiLaoExpress.UI.MVC.Controllers
{
    [Authorize]
    public class OpportunityController : AnexoBaseController
    {
        private readonly IOportunidadeService _service;
        private readonly ICargaService _serviceCarga;
        private readonly ILanceService _serviceLance;
        private readonly IFeedbackService _serviceFeedback;

        public OpportunityController(IOportunidadeService service, ICargaService serviceCarga, ILanceService serviceLance,
            IFeedbackService serviceFeedback)
        {
            _service = service;
            _serviceCarga = serviceCarga;
            _serviceLance = serviceLance;
            _serviceFeedback = serviceFeedback;
        }

        // GET: Opportunity
        public async Task<ActionResult> Index()
        {
            var lista = await _service.GetAllAsync();

            ViewBag.IsFornecedor = TipoUsuarioLogado == TypeOfUser.Fornecedor;


            return View(lista);
        }

        public async Task<ActionResult> MinhasOportunidades()
        {
            var lista = await _service.GetAllAsync(x => x.User.Id == IdUsuarioLogado);

            return View("Lista", lista);
        }

        public ActionResult Create()
        {
            ViewBag.CargaId = new SelectList(_serviceCarga.GetAll(x => x.UserId == IdUsuarioLogado), "Id", "Nome");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Oportunidade model, int? CargaId)
        {
            if (!CargaId.HasValue)
                ModelState.AddModelError("CargaId", "Escolha uma carga.");

            if (!ModelState.IsValid)
            {
                ViewBag.CargaId = new SelectList(_serviceCarga.GetAll(x => x.UserId == IdUsuarioLogado), "Id", "Nome", CargaId);

                return View(model);
            }

            model.UserId = IdUsuarioLogado;

            var carga = _serviceCarga.GetById(CargaId.Value);

            carga.Oportunidades.Add(model);

            _serviceCarga.Update(carga);

            return RedirectToAction("MinhasOportunidades");
        }

        public async Task<ActionResult> Edit(int Id)
        {
            var model = await _service.GetByIdAsync(Id);

            ViewBag.CargaId = new SelectList(_serviceCarga.GetAll(x => x.UserId == IdUsuarioLogado), "Id", "Nome", model.Cargas.FirstOrDefault().Id);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Oportunidade model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _service.UpdateAsync(model);

            return RedirectToAction("MinhasOportunidades");
        }

        public async Task<ActionResult> Details(int Id)
        {
            var model = await _service.GetByIdAsync(Id);
            return View(model);
        }

        public ActionResult Delete(int Id)
        {
            _service.Remove(Id);

            return RedirectToAction("MinhasOportunidades");
        }

        public ActionResult DetalharOportunidade(int Id)
        {
            var model = _service.GetById(Id);

            ViewBag.IsFornecedor = TipoUsuarioLogado == TypeOfUser.Fornecedor;
            
            if (model.DataColeta.AddDays(3).Date < DateTime.Now.Date)
            {
                if (!model.Lances.Any(x => x.Escolhida))
                {
                    Lance lance = model.Lances.OrderBy(x => x.Valor).ThenByDescending(x => x.DataColeta).ThenByDescending(x => x.DataEntrega).FirstOrDefault();

                    if (lance != null)
                    {
                        lance.Escolhida = true;

                        _service.Update(model);
                    }
                }

            }

            ViewBag.Encerrada = model.Lances.Any(x => x.Escolhida);
            ViewBag.AtivarFeedback = !_serviceFeedback.GetAll(x => x.Oportunidade.Id == model.Id).Any();
            return View(model);
        }

        public ActionResult SelecionarServico(int id)
        {
            var lance = _serviceLance.GetById(id);

            if (lance == null)
                return HttpNotFound();

            var lanceEscolhido = _serviceLance.GetAll(x => x.Escolhida && x.Oportunidade.Id == lance.Oportunidade.Id).FirstOrDefault();


            if (lanceEscolhido != null)
            {

                lanceEscolhido.Escolhida = false;

                _serviceLance.Update(lanceEscolhido);
            }
            lance.Escolhida = true;

            _serviceLance.Update(lance);

            return RedirectToAction("DetalharOportunidade", new { id = lance.Oportunidade.Id });
        }

    }
}

LeiLaoExpress.UI.MVC/Views/Opportunity/Create.cshtml
@model Oportunidade
@{
    ViewBag.Title = Text.Cadastrar;
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Create", null, new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label(Text.Origem, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Origem, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Origem, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.Destino, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Destino, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Destino, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.DataColeta, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.DataColeta, new { @class = "form-control datepicker" })
                        @Html.ValidationMessageFor(m => m.DataColeta, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.DataEntrega, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.DataEntrega, new { @class = "form-control datepicker" })
                        @Html.ValidationMessageFor(m => m.DataEntrega, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Carga", new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownList("CargaId",null, new { @class = "form-control" })
                        @Html.ValidationMessage("CargaId", "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-success" value="@Text.Cadastrar" />
                        @Html.ActionLink(Text.Voltar, "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            }
        </section>
    </div>
</div>

LeiLaoExpress.UI.MVC/Views/Opportunity/Details.cshtml
@model Oportunidade
@{
    ViewBag.Title = Text.Detalhar;
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form class="form-horizontal">
                @Html.HiddenFor(X => X.Id)
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label(Text.Origem, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Origem, new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(m => m.Origem, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.Destino, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Destino, new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(m => m.Destino, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.DataColeta, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.DataColeta, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(m => m.DataColeta, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.DataEntrega, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.DataEntrega, "{0:dd/MM/yyyy}", new { @class = "form-control" , @readonly="readonly" })
                        @Html.ValidationMessageFor(m => m.DataEntrega, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink(Text.Editar, "Edit", new { Id = Model.Id }, new { @class = "btn btn-warning" })
                        @Html.ActionLink(Text.Voltar, "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>

LeiLaoExpress.UI.MVC/Views/Opportunity/DetalharOportunidade.cshtml
@model LeiLaoExpress.Domain.Model.Oportunidade

@{
    ViewBag.Title = Text.DetalharDaOportunidade;
}

<h2>@ViewBag.Title</h2>

<div>
    <div class="row">
        <div class="col-md-4">
            <h4>
                Serão aceito lances até o fim do leilão ou até o dono da oportunidade selecionar um fornecedor.
            </h4>
        </div>
        @if ((bool)ViewBag.Encerrada)
        {
            <h4 class="pull-rigth texto-right text-danger">Oportunidade encerrada.</h4>
            if (!(bool)ViewBag.IsFornecedor && ViewBag.AtivarFeedback)
            {
                <text>
                    @Ajax.ActionLink("Feedback", "ModalCreate", "Feedback", new { idOportunidade = Model.Id }, new AjaxOptions { UpdateTargetId = "main-modal", HttpMethod = "GET" }, new { @class = "btn btn-warning pull-right " })
                </text>
            }
        }
        else
        {
            <h4 class="pull-rigth texto-right">Tempo restante para encerramento da Oportunidade</h4>
            <div id="contador" class="col-md-4 pull-right"></div>
        }
    </div>
    <hr />
    <div class="">
        <div class="row">
            <div class="col-md-6 pdm">
                <div class="form-group">
                    @Html.LabelFor(model => model.Origem, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Origem, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="col-md-6 pdm">
                <div class="form-group">
                    @Html.LabelFor(model => model.Destino, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Destino, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="col-md-6 pdm">
                <div class="form-group">
                    @Html.Label(Text.DataColeta, htmlAttributes: new { @class = "control-label " })
                    @Html.TextBoxFor(model => model.DataColeta, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "readonly" })
                </div>

            </div>
            <div class="col-md-6 pdm">
                <div class="form-group">
                    @Html.Label(Text.DataEntrega, htmlAttributes: new { @class = "control-label " })
                    @Html.TextBoxFor(model => model.DataEntrega, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
        </div>
    </div>
</div>
<hr />
@if (Model.Lances.Any())
{
    <div class="container">
        <h3 class="text-center">Lances</h3>
        <hr />
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>@Text.Fornecedor</td>
                    <td>@Text.DataColeta</td>
                    <td>@Text.DataEntrega</td>
                    <td>@Text.Valor</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Lances.OrderBy(x => x.Valor).ThenByDescending(x => x.DataColeta).ThenByDescending(x => x.DataEntrega))
                {
                    <tr class="@(item.Escolhida ? "success":"")">
                        <td>@item.Fornecedor.Nome</td>
                        <td>@item.DataColeta.ToString("dd/MM/yyyy")</td>
                        <td>@item.DataEntrega.ToString("dd/MM/yyyy")</td>
                        <td>R$@item.Valor</td>
                        <td>
                            @if (!(bool)ViewBag.IsFornecedor && !(bool)ViewBag.Encerrada)
                            {
                                @Html.ActionLink("Selecionar serviço", "SelecionarServico", new { id = item.Id }, new { @class = "btn btn-success" })
                            }
                            @Ajax.ActionLink("Reputação", "Index", "Feedback", new { id = item.Fornecedor.UserId }, new AjaxOptions { UpdateTargetId = "main-modal", HttpMethod = "GET" }, new { @class = "btn btn-info" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

}
<p>
    @if ((bool)ViewBag.IsFornecedor)
    {
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
    }
    else
    {
        @Html.ActionLink("Voltar", "MinhasOportunidades", null, new { @class = "btn btn-primary" })
    }
    @if ((bool)ViewBag.IsFornecedor && Model.DataColeta.AddDays(3).Date > DateTime.Now.Date)
    {
        @Ajax.ActionLink(Text.DarUmLance, "LanceModal", "Lance", new { OportunidadeId = Model.Id }, new AjaxOptions { UpdateTargetId = "main-modal", HttpMethod = "GET" }, new { @class = "btn btn-info" })
    }
</p>


@section scripts{

    @Scripts.Render("~/bundles/jqueryval")

    <link href="~/Content/jquery.countdown.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.plugin.js"></script>
    <script src="~/Scripts/jquery.countdown.js"></script>
    <script src="~/Scripts/jquery.countdown-pt-BR.js"></script>
    <script>
        $(function () {
            var encerramento = new Date(@Model.DataColeta.AddDays(-3).Year, @Model.DataColeta.AddDays(-3).Month -1, @Model.DataColeta.AddDays(-3).Day);
            $('#contador').countdown({ until: encerramento, format: 'yowdHMS' });
        });
    </script>
}

LeiLaoExpress.UI.MVC/Views/Opportunity/Edit.cshtml
@model Oportunidade
@{
    ViewBag.Title = Text.Editar;
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Edit", null, new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(X => X.Id)
                @Html.HiddenFor(X => X.UserId)
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label(Text.Origem, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Origem, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Origem, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.Destino, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Destino, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Destino, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.DataColeta, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.DataColeta, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                        @Html.ValidationMessageFor(m => m.DataColeta, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Text.DataEntrega, new { @class = "col-md-2 control-label", @for = "DataEntrega" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.DataEntrega, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                        @Html.ValidationMessageFor(m => m.DataEntrega, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Carga", new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownList("CargaId", null, new { @class = "form-control", disabled = "disabled" })
                        @Html.ValidationMessage("CargaId", "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-warning" value="@Text.Salvar" />
                        @Html.ActionLink(Text.Cancelar, "Index", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
        </section>
    </div>
</div>

LeiLaoExpress.UI.MVC/Views/Opportunity/Index.cshtml
@model IEnumerable<Oportunidade>

@{
    ViewBag.Title = Text.Oportunidades;
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName(Text.Origem)
            </th>
            <th>
                @Html.DisplayName(Text.Destino)
            </th>
            <th>
                @Html.DisplayName(Text.DataColeta)
            </th>
            <th>
                @Html.DisplayName(Text.DataEntrega)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Origem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destino)
                </td>
                <td>
                    @item.DataColeta.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @item.DataEntrega.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @if ((bool)ViewBag.IsFornecedor && !item.Lances.Any(x=>x.Escolhida))
                    {
                        <text>
                    @Html.ActionLink(Text.DarUmLance, "Create", "Lance", new { idOportunidade = item.Id }, new { @class = "btn btn-success" })
</text>
                    }
                    @Html.ActionLink(Text.Detalhar, "DetalharOportunidade", null, new { Id = item.Id }, new { @class = "btn btn-info" })
                </td>
            </tr>
        }
    </tbody>
</table>

LeiLaoExpress.UI.MVC/Views/Opportunity/Lista.cshtml
@model IEnumerable<Oportunidade>

@{
    ViewBag.Title = Text.Oportunidades;
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink(Text.Cadastrar, "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName(Text.Origem)
            </th>
            <th>
                @Html.DisplayName(Text.Destino)
            </th>
            <th>
                @Html.DisplayName(Text.DataColeta)
            </th>
            <th>
                @Html.DisplayName(Text.DataEntrega)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Origem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destino)
                </td>
                <td>
                    @item.DataColeta.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @item.DataEntrega.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.ActionLink(Text.Editar, "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                    @Html.ActionLink(Text.Deletar, "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                    @Html.ActionLink("Gerenciar Oportunidade", "DetalharOportunidade", new { id = item.Id }, new { @class = "btn btn-info" })
                </td>
            </tr>
        }
    </tbody>
</table>